### PR TITLE
Delete mergebot.yml

### PR DESCRIPTION
**Pull request by mihaitabamburic**

### CODE REVIEW

**Comment by stefanfinseth** [comment]
Why? 🤔

**Comment by mihaitabamburic** [comment]
> Why? 🤔

Because mergebot cannot merge mergebot PRs without some extra effort, so this workflow just runs and fails every single time now

**Comment by stefanfinseth** [comment]
> > Why? 🤔
> 
> Because mergebot cannot merge mergebot PRs without some extra effort, so this workflow just runs and fails every single time now

Would have made a great description on the PR 😄

**Review by stefanfinseth — APPROVED** [review]

**Comment by mihaitabamburic** [comment]
> > > Why? 🤔
> > 
> > 
> > Because mergebot cannot merge mergebot PRs without some extra effort, so this workflow just runs and fails every single time now
> 
> Would have made a great description on the PR 😄

That's right, I shall add it for next time I do something. The context is definitely very particular to this repo

**Pull request merged**
